---
apiVersion: v2
appVersion: 10.9.1
description: Jellyfin is a Free Software Media System
name: jellyfin
version: 9.9.4
kubeVersion: ">=1.16.0-0"
keywords:
  - jellyfin
  - plex
  - emby
home: https://github.com/h-s-c/helm-charts/jellyfin
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-solid-black.svg
sources:
  - https://hub.docker.com/r/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin
maintainers:
  - name: Kevin Schmidt
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
